[default]
extend-ignore-identifiers-re = [
    "thm",
    "plas",
    "iy",
    "gam",
    "sav",
    "Salaris",
    "Comput",
    "nd",
    "dum",
    "Ptd",
    "AGS",
    "GAM",
    "ETHE",
    "idel",
    "nce",
    "ba",
    "ths",
    "ND",
    "ine",
    "Puls",
    "nin",
    "nam",
    "ags",
    "delt",
    "alog",
    "yout",
    "rhe",
    "NUMER",
    "ETO",
    "UE",
    "FASE",
    "EDE",
    "Commun",
    "coul",
    "Numer",
    "Nd",
    "struc",
    "FO",
    "dout",
    "Strang",
    "IY",
    "NINTY",
    "TEMR",
    "stopp",
    "Shepard",
    "DUM",
    "ACI",
    "PRESSE",
    "Finf",
    "ACN",
    "PN",
    "Antia",
    "Shal",
    "ded",
    "SHS",
    "arry",
    "SROL",
    "Coul",
    "daa",
    "smal",
    "contro",
    "SROT",
    "implct",
    "thi",
    "maks",
    "Ba",
    "Nin",
    "tilda",
    "alph",
    "pn",
    "thet",
    "antia",
    "accpt",
    "Ser",
    "anc",
]

[files]
extend-exclude = ["adipls","stella"]
